### ISSUE TITLE
Can't build html

### ISSUE THREAD

**Issue by d954mas** [andsve/def-diags#1]
Can't make html build.I don't need diags in html. I want build working html without diags

![2018-07-07_18-06-54](https://user-images.githubusercontent.com/2655263/42412217-91410646-8210-11e8-8724-a86f6c931eed.png)

**Comment by subsoap** [comment]
Here is a patch, I made a pull request too.

https://github.com/subsoap/def-diags/archive/master.zip

**Comment by andsve** [comment]
Merged pr #2 , thanks! 👍
